### ISSUE TITLE
How to make it work?

### ISSUE THREAD

**Issue by lyxhaven** [zakkak/qa-ldap-login#12]
I followed the steps one by one and how does it work?
I tried to use my username and password from ldap to login but failed.
It seemed not recognizing my account (user not found).

**Comment by Andiego** [comment]
Hi zakkak,

I have a similar problem:
Warning: ldap_search(): Search: Operations error in C:\wamp64\www\question2answer-1.7.4\qa-plugin\qa-ldap-login\ActiveDirectoryLDAPServer.php on line 24
and
Warning: ldap_get_entries() expects parameter 2 to be resource, boolean given in C:\wamp64\www\question2answer-1.7.4\qa-plugin\qa-ldap-login\ActiveDirectoryLDAPServer.php on line 25

Is it possible to help me in this case? Thanks

**Comment by zakkak** [comment]
Unfortunately I can't help you.  

Maybe your case is similar to the one here https://stackoverflow.com/questions/17742751/ldap-operations-error
