### ISSUE TITLE
How to install the plugin in Q2A 1.7

### ISSUE THREAD

**Issue by indigo423** [zakkak/qa-ldap-login#17]
The README to install is outdated. Line 59 doesn't exist anymore in `qa-include/qa-page-login.php`
See also here: https://github.com/q2a/question2answer/blob/v1.7-beta/qa-include/qa-page-login.php.

How can you install the plugin in 1.7 which is the recommended version on the project page?

**Comment by zakkak** [comment]
I am no longer using Q2A, as a result I cannot give you an ETA for this.  Please issue a pull request if you fix it before I do. Thanks for the notification.

**Comment by indigo423** [comment]
I'm not familiar with development in q2a, so I can't do anything in this topic. I'll appreciate your honor feedback. Thank you.

**Comment by EveryOtherUsernameWasAlreadyTaken** [comment]
Looking at [1.6.3 ](https://github.com/q2a/question2answer/blob/8274a6e876c3682e878febfb02080a2291f7612e/qa-include/qa-page-login.php), I see some includes in line 55 and 56
			require_once QA_INCLUDE_DIR.'qa-db-users.php';
			require_once QA_INCLUDE_DIR.'qa-db-selects.php';

These lines are [now](https://github.com/q2a/question2answer/blob/f8b7dfe3cd6c6cc71a1572686efa32168aa7380d/qa-include/pages/login.php) in /qa-include/pages/login.php, line 51 and 52. My guess is to add it there.

**Comment by zakkak** [comment]
Please try adding 
```
	require_once QA_INCLUDE_DIR.'../qa-plugin/qa-ldap-login/qa-ldap-process.php';
```
at line 61 in `qa-include/pages/login.php`

**Comment by raindylong** [comment]
It's work on version 1.7 , but it took about 1min for the LDAP user to login for the first time (the db is locked during this minute) , and everything is ok when the same ldap user login for the second time , why & how to fix ?

**Comment by zakkak** [comment]
I can't think what could be causing this.  How long does it take to normally register a new user?

**Comment by raindylong** [comment]
About 1m25s  for the LDAP user to login for the first time , after that , each login request is fast . Normally register process is all ok at the same time .

**Comment by zakkak** [comment]
Sounds really strange.  I still cannot think of any possible reasons
that may cause this behavior.

**Comment by zakkak** [comment]
Closed by https://github.com/zakkak/qa-ldap-login/commit/6a1797037846ffda4deb9f84df65fcb11f14ff50
