### ISSUE TITLE
After set ldap and try run with latest q2a version, blank screen

### ISSUE THREAD

**Issue by Orthophilos** [zakkak/qa-ldap-login#18]
HI, I tried to configurate yuor plugin with my ldap, after try to login in q2a is giving me back a blank screen ( 500 error), tried hard a lot ways, not working . Do you have some clue?  Issue opened as our discussion in email.

**Comment by lvptn** [comment]
I have the same issue. Please see screenshots for steps. I have a wamp server running with all plugins, however after configuring plugin, i get the 500 error as well, removing the line of code on the login.php page solves that issue temporarily, however the plugin does not work as intended then.

**Comment by zakkak** [comment]
Can you please try it with version 1.7 (http://question2answer.org/releases/question2answer-1.7.zip) instead of 1.7.1 and let me know if it works?

**Comment by lvptn** [comment]
i receive the same error, please see the attached screenshot after trying to log in with an active directory username/password as WELL as the local admin username from q2a. 
![q2a](https://cloud.githubusercontent.com/assets/15197655/10581452/5d9be648-7648-11e5-92ad-bfd34f296d5c.PNG)

**Comment by zakkak** [comment]
The error says that `C:/wamp/www/q2a/qa-plugin/qa-ldap-login/qa-ldap-process.php` could not be found.

That means that either qa-ldap-login is not placed in the qa-plugin directory or it is there but doesn't have the right permission.  In the second case please check the ownership of the default plugins and apply the same ownership and access rights to qa-ldap-plugin.

**Comment by lvptn** [comment]
Hello,

All permissions are set the same and recursively/concurrently. I still receive the same error. This issue is the same issue I have on my LAMP server/production server.

**Comment by zakkak** [comment]
I can't think of anything else.  The error is clear about not finding the file to include, if it is not a permissions error and the file is present at the correct path I do not know what else it could be.

**Comment by lvptn** [comment]
The error I receive on my production server is the 505 error, which as the correct permissions as well.
