### ISSUE TITLE
Call to nav_list missing third argument

### ISSUE THREAD

**Issue by DoubleAG008** [zakkak/qa-ldap-login#19]
In ldap-login-layer.php the nav_list method is overridden and the parent method is called at the end of the overridden method.  However, the $level argument is not passed to the parent method.  This causes HTML to be generated that is missing a class for what the level should be.

To fix this issue, the $level argument needs to be passed into the parent method call.

**Comment by zakkak** [comment]
If you have tested the above please issue a PR with the fix.

**Comment by zakkak** [comment]
Merged, thanks!
